export const cardData = [
  {
    title: "Sketch from A to Z: for app designer",
    desc: "Proposal indulged no do sociable he throwing settling.",
    tag: "All level",
    rating: "4/5.0",
    time: "12h 56m",
    lectures: "15 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Web Design",
  },
  {
    title: "HTML & CSS Basics",
    desc: "Learn the foundation of modern web design.",
    tag: "Beginner",
    rating: "4.3/5.0",
    time: "8h 40m",
    lectures: "12 lectures",
    image: "/dd1.png",
    isLiked: true,
    category: "Web Design",
  },
  {
    title: "Advanced UI with Tailwind",
    desc: "Design pixel-perfect UIs using Tailwind CSS.",
    tag: "Intermediate",
    rating: "4.7/5.0",
    time: "6h 10m",
    lectures: "10 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Web Design",
  },
  {
    title: "JavaScript for Designers",
    desc: "Make your websites interactive and dynamic.",
    tag: "All level",
    rating: "4.5/5.0",
    time: "9h 25m",
    lectures: "14 lectures",
    image: "/dd1.png",
    isLiked: true,
    category: "Web Design",
  },
  {
    title: "Figma to Code Mastery",
    desc: "Convert Figma files into responsive websites.",
    tag: "Intermediate",
    rating: "4.6/5.0",
    time: "7h 20m",
    lectures: "16 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Web Design",
  },

  {
    title: "Master React.js from Scratch",
    desc: "Build modern apps using React and hooks.",
    tag: "Beginner",
    rating: "4.8/5.0",
    time: "14h 50m",
    lectures: "22 lectures",
    image: "/dd1.png",
    isLiked: true,
    category: "Development",
  },
  {
    title: "Node.js & Express Bootcamp",
    desc: "Server-side development made simple.",
    tag: "Intermediate",
    rating: "4.4/5.0",
    time: "11h 15m",
    lectures: "18 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Development",
  },
  {
    title: "Fullstack Web Dev Guide",
    desc: "Become a fullstack MERN developer.",
    tag: "All level",
    rating: "4.9/5.0",
    time: "20h 10m",
    lectures: "30 lectures",
    image: "/dd1.png",
    isLiked: true,
    category: "Development",
  },
  {
    title: "API Integration with Axios",
    desc: "Connect your app to any REST API.",
    tag: "Beginner",
    rating: "4.2/5.0",
    time: "5h 30m",
    lectures: "9 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Development",
  },
  {
    title: "Deep Learning with React-Native",
    desc: "Far advanced settling say finished raillery.",
    tag: "Beginner",
    rating: "4/5.0",
    time: "11h 5m",
    lectures: "22 lectures",
    image: "/dd1.png",
    isLiked: true,
    category: "Development",
  },

  {
    title: "Graphic Design Masterclass",
    desc: "Design stunning visuals that impress.",
    tag: "Beginner",
    rating: "4.5/5.0",
    time: "10h 30m",
    lectures: "20 lectures",
    image: "/dd1.png",
    isLiked: true,
    category: "Graphic Design",
  },
  {
    title: "Photoshop Fundamentals",
    desc: "Learn photo editing like a pro.",
    tag: "Beginner",
    rating: "4.1/5.0",
    time: "8h 15m",
    lectures: "13 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Graphic Design",
  },
  {
    title: "Create a Design System in Figma",
    desc: "Build scalable design systems.",
    tag: "Beginner",
    rating: "4.5/5.0",
    time: "9h 15m",
    lectures: "18 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Graphic Design",
  },
  {
    title: "Logo Design from Scratch",
    desc: "Craft brand identities that stand out.",
    tag: "Intermediate",
    rating: "4.6/5.0",
    time: "6h 45m",
    lectures: "11 lectures",
    image: "/dd1.png",
    isLiked: true,
    category: "Graphic Design",
  },
  {
    title: "Illustrator for Beginners",
    desc: "Master vector graphics and design.",
    tag: "Beginner",
    rating: "4.3/5.0",
    time: "7h 50m",
    lectures: "15 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Graphic Design",
  },

  {
    title: "Social Media Marketing 101",
    desc: "Grow your brand online strategically.",
    tag: "Beginner",
    rating: "4.4/5.0",
    time: "6h 20m",
    lectures: "12 lectures",
    image: "/dd1.png",
    isLiked: true,
    category: "Marketing",
  },
  {
    title: "SEO Fundamentals",
    desc: "Boost traffic and optimize content.",
    tag: "Intermediate",
    rating: "4.6/5.0",
    time: "5h 30m",
    lectures: "10 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Marketing",
  },
  {
    title: "Email Campaigns that Convert",
    desc: "Email strategies that get clicks.",
    tag: "All level",
    rating: "4.2/5.0",
    time: "4h 45m",
    lectures: "9 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Marketing",
  },
  {
    title: "Instagram Ads Mastery",
    desc: "Maximize ROI from social campaigns.",
    tag: "Advanced",
    rating: "4.7/5.0",
    time: "6h 10m",
    lectures: "11 lectures",
    image: "/dd1.png",
    isLiked: true,
    category: "Marketing",
  },
  {
    title: "Content Marketing Bootcamp",
    desc: "Learn to craft viral content.",
    tag: "Intermediate",
    rating: "4.4/5.0",
    time: "7h 30m",
    lectures: "14 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Marketing",
  },

  {
    title: "Finance for Non-Finance",
    desc: "Understand finance without a degree.",
    tag: "Beginner",
    rating: "4.1/5.0",
    time: "6h 40m",
    lectures: "10 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Finance",
  },
  {
    title: "Investment Strategies 2024",
    desc: "Smart investing explained simply.",
    tag: "Intermediate",
    rating: "4.3/5.0",
    time: "8h 20m",
    lectures: "13 lectures",
    image: "/dd1.png",
    isLiked: true,
    category: "Finance",
  },
  {
    title: "Accounting Basics",
    desc: "Master balance sheets and ledgers.",
    tag: "Beginner",
    rating: "4.2/5.0",
    time: "7h 10m",
    lectures: "12 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Finance",
  },
  {
    title: "Personal Budgeting Guide",
    desc: "Plan and control your finances.",
    tag: "All level",
    rating: "4.5/5.0",
    time: "5h 35m",
    lectures: "11 lectures",
    image: "/dd1.png",
    isLiked: true,
    category: "Finance",
  },
  {
    title: "Cryptocurrency Essentials",
    desc: "Intro to blockchain and crypto.",
    tag: "Beginner",
    rating: "4.6/5.0",
    time: "6h 25m",
    lectures: "10 lectures",
    image: "/dd1.png",
    isLiked: false,
    category: "Finance",
  },
];



export const courses = [
  {
    id: 1,
    title: "React for Beginners",
    image: "/images/react-course.jpg",
    rating: 4.5,
    author: "John Doe",
    price: "$49.99",
  },
  {
    id: 2,
    title: "Advanced Node.js",
    image: "/images/node-course.jpg",
    rating: 4.8,
    author: "Jane Smith",
    price: "$59.99",
  },
  {
    id: 3,
    title: "Mastering Tailwind CSS",
    image: "/images/tailwind-course.jpg",
    rating: 4.6,
    author: "Chris Johnson",
    price: "$39.99",
  },
  {
    id: 4,
    title: "Fullstack MERN Bootcamp",
    image: "/images/mern-course.jpg",
    rating: 4.9,
    author: "Emily Clark",
    price: "$99.99",
  },
  {
    id: 5,
    title: "Next.js Zero to Hero",
    image: "/images/nextjs-course.jpg",
    rating: 4.7,
    author: "David Miller",
    price: "$69.99",
  },
  {
    id: 6,
    title: "TypeScript Essentials",
    image: "/images/typescript-course.jpg",
    rating: 4.4,
    author: "Sophia Lee",
    price: "$45.00",
  },
  {
    id: 7,
    title: "GraphQL with Apollo",
    image: "/images/graphql-course.jpg",
    rating: 4.3,
    author: "Michael Scott",
    price: "$55.99",
  },
  {
    id: 8,
    title: "Docker for Developers",
    image: "/images/docker-course.jpg",
    rating: 4.6,
    author: "Angela White",
    price: "$49.00",
  },
  {
    id: 9,
    title: "Firebase Crash Course",
    image: "/images/firebase-course.jpg",
    rating: 4.5,
    author: "Ryan Gomez",
    price: "$42.99",
  },
  {
    id: 10,
    title: "Data Structures in JS",
    image: "/images/data-structures.jpg",
    rating: 4.8,
    author: "Linda Baker",
    price: "$57.49",
  },
];
